import pennylane as qp

def circuit(name : str = None, num : str = None):
    """This function will take either the name of a circuit or it number and return a function corresponding to that circuit.
    """
    circuits = {
        "SU4": 31,
        "Brickwall": 32,
    }
    if num is None:
        if name is None:
            raise ValueError("You must provide either a circuit name or a circuit number.")
        num = circuits[name]
    
    

def full_SU2(params, wires = None):
    """ 
    params : tenor of shape ( num_wires, 3)
    """
    if wires is None:
        wires = list(range(params.shape[0]))
    num_wires, _ = params.shape
    for i in range(num_wires):
        qp.Rot(*params[i], wires=wires[i])

def two_rotations(params, wires = None):
    """ 
    params : tenor of shape (num_wires, 2)
    """
    num_wires, _ = params.shape
    if wires is None:
        wires = list(range(num_wires))
    for i in range(num_wires):
        qp.RY(params[i, 0], wires=wires[i])
        qp.RX(params[i, 1], wires=wires[i])

def CNOT_cascade(wires , circulare = False, ascending = False):
    """ 
    wires : list of wires to apply the CNOT cascade on
    circulare : if True, apply a CNOT from the last wire to the first wire
    ascending : if True, apply the CNOTs in ascending order, else in descending order
    """
    if ascending:
        for i in range(len(wires) - 1):
            qp.CNOT(wires=[wires[i], wires[i + 1]])
        if circulare:
            qp.CNOT(wires=[wires[-1], wires[0]])
    else:
        for i in range(len(wires) - 1, 0, -1):
            qp.CNOT(wires=[wires[i], wires[i - 1]])
        if circulare:
            qp.CNOT(wires=[wires[0], wires[-1]])




#### Code generated by Claude from my qiskit code;

def rx_rz_layer(params, wires):
    """Apply RX and RZ to each wire. params shape: (num_wires, 2)"""
    for i, w in enumerate(wires):
        qp.RX(params[i, 0], wires=w)
        qp.RZ(params[i, 1], wires=w)


def parametrized_CZ_chain(params, wires):
    """Apply parametrized CZ (CP) on nearest-neighbor pairs. params shape: (num_wires-1,)"""
    for i in range(len(wires) - 1):
        qp.ControlledPhaseShift(params[i], wires=[wires[i], wires[i + 1]])


def parametrized_CX_chain(params, wires):
    """Apply parametrized CX (H-CP-H) on nearest-neighbor pairs. params shape: (num_wires-1,)"""
    for i in range(len(wires) - 1):
        qp.Hadamard(wires=wires[i])
        qp.ControlledPhaseShift(params[i], wires=[wires[i], wires[i + 1]])
        qp.Hadamard(wires=wires[i])


def circuit_set(name: str = None, num: int = None):
    """Return a function corresponding to the named or numbered circuit.

    Circuits 1–19 are direct translations of the Qiskit circuit_set circuits.
    """
    
    circuit_names = {
        "SU4": 31,
        "Brickwall": 32,
    }
    # extend as needed

    if num is None:
        if name is None:
            raise ValueError("You must provide either a circuit name or a circuit number.")
        num = circuit_names[name]

    # ------------------------------------------------------------------
    # Circuit 1: RX-RZ layers, no entanglement
    # params shape: (reps, num_wires, 2)
    # ------------------------------------------------------------------
    if num == 1:
        def circ1(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i], wires)

        return circ1

    # ------------------------------------------------------------------
    # Circuit 2: RX-RZ + CNOT cascade (nearest-neighbor, fixed)
    # params shape: (reps, num_wires, 2)
    # ------------------------------------------------------------------
    elif num == 2:
        def circ2(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i], wires)
                CNOT_cascade(wires, ascending=True)

        return circ2

    # ------------------------------------------------------------------
    # Circuit 3: RX-RZ + parametrized CZ chain
    # params shape: (reps, num_wires, 2) for rotations + (reps, num_wires-1) for CZ angles
    # Packed as params shape: (reps, 2*num_wires + (num_wires-1))
    # ------------------------------------------------------------------
    elif num == 3:
        def circ3(params, wires=None):
            reps, num_wires, _ = params.shape  # params: (reps, num_wires, 3)
            # params[:, :, :2] = RX/RZ angles, params[:, :num_wires-1, 2] = CP angles
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                parametrized_CZ_chain(params[i, :num_wires - 1, 2], wires)

        return circ3

    # ------------------------------------------------------------------
    # Circuit 4: RX-RZ + parametrized CX (H-CP-H) chain
    # params shape: (reps, num_wires, 3)  — same layout as circuit 3
    # ------------------------------------------------------------------
    elif num == 4:
        def circ4(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                parametrized_CX_chain(params[i, :num_wires - 1, 2], wires)

        return circ4

    # ------------------------------------------------------------------
    # Circuit 5: RX-RZ, all-to-all parametrized CZ, RX-RZ
    # params shape: (reps, num_wires, 4 + num_wires - 1)
    # Layout per rep: [RX-RZ block] [all-to-all CZ] [RX-RZ block]
    # Simplified packing: params shape (reps, 4*num_wires + num_wires*(num_wires-1))
    # Here we use explicit named slices for clarity.
    # ------------------------------------------------------------------
    elif num == 5:
        def circ5(params, wires=None):
            """
            params shape: (reps, num_wires, 2 + (num_wires - 1) + 2)
            params[:, :, 0:2]                      = first RX-RZ block
            params[:, i, 2:2+(num_wires-1)]        = CP angles for qubit i to all others
            params[:, :, 2+(num_wires-1):]         = second RX-RZ block (2 angles)
            """
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            n_cp = num_wires - 1  # angles per qubit (skip self)
            for i in range(reps):
                # First RX-RZ
                rx_rz_layer(params[i, :, :2], wires)
                # All-to-all parametrized CZ
                for q in range(num_wires):
                    cp_idx = 0
                    for q2 in range(num_wires):
                        if q2 != q:
                            qp.ControlledPhaseShift(params[i, q, 2 + cp_idx], wires=[wires[q], wires[q2]])
                            cp_idx += 1
                # Second RX-RZ
                rx_rz_layer(params[i, :, 2 + n_cp:], wires)

        return circ5

    # ------------------------------------------------------------------
    # Circuit 6: RX-RZ, all-to-all parametrized CX (H-CP-H), RX-RZ
    # Same shape as circuit 5
    # ------------------------------------------------------------------
    elif num == 6:
        def circ6(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            n_cp = num_wires - 1
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                for q in range(num_wires):
                    cp_idx = 0
                    for q2 in range(num_wires):
                        if q2 != q:
                            qp.Hadamard(wires=wires[q])
                            qp.ControlledPhaseShift(params[i, q, 2 + cp_idx], wires=[wires[q], wires[q2]])
                            qp.Hadamard(wires=wires[q])
                            cp_idx += 1
                rx_rz_layer(params[i, :, 2 + n_cp:], wires)

        return circ6

    # ------------------------------------------------------------------
    # Circuit 7: RX-RZ, staggered parametrized CZ (even pairs then odd pairs), RX-RZ
    # params shape: (reps, num_wires, 2) + stagger CP angles
    # Packed: (reps, 4*num_wires + num_wires//2 + (num_wires-1)//2)
    # Simplified: params shape (reps, num_wires, 5)
    #   params[:, :, 0:2]              = first RX-RZ
    #   params[:, :num_wires//2, 5]    = even-pair CP angles
    #   params[:, :, 2:4]              = second RX-RZ
    #   params[:, :(num_wires-1)//2, 5]= odd-pair CP angles   (in separate tensor below)
    # For simplicity we split into separate param tensors matching the Qiskit structure.
    # ------------------------------------------------------------------
    elif num == 7:
        def circ7(params, wires=None):
            """
            params : (reps, num_wires, 5)  — packed params for RX-RZ and CP angles
            """
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i,:,:2], wires)
                for q in (range(0, num_wires - 1, 2)):
                    qp.ControlledPhaseShift(params[i, q, 4], wires=[wires[q], wires[q + 1]])
                rx_rz_layer(params[i,:,2:4], wires)
                for q_idx, q in enumerate(range(1, num_wires - 1, 2)):
                    qp.ControlledPhaseShift(params[i, q_idx, 4], wires=[wires[q], wires[q + 1]])

        return circ7

    # ------------------------------------------------------------------
    # Circuit 8: same as 7 but with parametrized CX (H-CP-H)
    # ------------------------------------------------------------------
    elif num == 8:
        def circ8(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i,:,:2], wires)
                for q_idx, q in enumerate(range(0, num_wires - 1, 2)):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q_idx, 4], wires=[wires[q], wires[q + 1]])
                    qp.Hadamard(wires=wires[q])
                rx_rz_layer(params[i,:,2:4], wires)
                for q_idx, q in enumerate(range(1, num_wires - 1, 2)):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q_idx, 4], wires=[wires[q], wires[q + 1]])
                    qp.Hadamard(wires=wires[q])

        return circ8

    # ------------------------------------------------------------------
    # Circuit 9: H layer, CZ chain (fixed), RX layer
    # params shape: (reps, num_wires)
    # ------------------------------------------------------------------
    elif num == 9:
        def circ9(params, wires=None):
            reps, num_wires = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for w in wires:
                    qp.Hadamard(wires=w)
                for q in range(num_wires - 1):
                    qp.CZ(wires=[wires[q], wires[q + 1]])
                for q in range(num_wires):
                    qp.RX(params[i, q], wires=wires[q])

        return circ9

    # ------------------------------------------------------------------
    # Circuit 10: CZ chain with wrap-around + RY layer
    # params shape: (reps, num_wires)
    # ------------------------------------------------------------------
    elif num == 10:
        def circ10(params, wires=None):
            reps, num_wires = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires - 1):
                    qp.CZ(wires=[wires[q], wires[q + 1]])
                qp.CZ(wires=[wires[num_wires - 1], wires[0]])
                for q in range(num_wires):
                    qp.RY(params[i, q], wires=wires[q])

        return circ10

    # ------------------------------------------------------------------
    # Circuit 11: RY-RZ, even CNOT, inner RY-RZ, odd CNOT
    # params shape: (reps, num_wires, 2) for first block
    #               (reps, num_wires-2, 2) for inner block
    # ------------------------------------------------------------------
    elif num == 11:
        def circ11(params, wires=None):
            """
            params_outer shape: (reps, num_wires, 2)   — RY+RZ on all wires
            params_inner shape: (reps, num_wires-2, 2) — RY+RZ on inner wires (1..num_wires-2)
            """
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires):
                    qp.RY(params[i, q, 0], wires=wires[q])
                    qp.RZ(params[i, q, 1], wires=wires[q])
                for q in range(0, num_wires - 1, 2):
                    qp.CNOT(wires=[wires[q], wires[q + 1]])
                for q_idx, q in enumerate(range(1, num_wires - 1)):
                    qp.RY(params[i, q_idx, 0], wires=wires[q])
                    qp.RZ(params[i, q_idx, 1], wires=wires[q])
                for q in range(1, num_wires - 1, 2):
                    qp.CNOT(wires=[wires[q], wires[q + 1]])

        return circ11

    # ------------------------------------------------------------------
    # Circuit 12: same as 11 but with CZ instead of CNOT
    # ------------------------------------------------------------------
    elif num == 12:
        def circ12(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires):
                    qp.RY(params[i, q, 0], wires=wires[q])
                    qp.RZ(params[i, q, 1], wires=wires[q])
                for q in range(0, num_wires - 1, 2):
                    qp.CZ(wires=[wires[q], wires[q + 1]])
                for q_idx, q in enumerate(range(1, num_wires - 1)):
                    qp.RY(params[i, q_idx, 0], wires=wires[q])
                    qp.RZ(params[i, q_idx, 1], wires=wires[q])
                for q in range(1, num_wires - 1, 2):
                    qp.CZ(wires=[wires[q], wires[q + 1]])

        return circ12

    # ------------------------------------------------------------------
    # Circuit 13: RY, circular CP forward, RY, circular CP backward
    # params shape: (reps, num_wires, 4)
    #   [:, :, 0] = first RY, [:, :, 1] = CP forward
    #   [:, :, 2] = second RY, [:, :, 3] = CP backward
    # ------------------------------------------------------------------
    elif num == 13:
        def circ13(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires):
                    qp.RY(params[i, q, 0], wires=wires[q])
                for q in range(num_wires):
                    qp.ControlledPhaseShift(params[i, q, 1], wires=[wires[q], wires[(q + 1) % num_wires]])
                for q in range(num_wires):
                    qp.RY(params[i, q, 2], wires=wires[q])
                for q in range(num_wires):
                    qp.ControlledPhaseShift(params[i, q, 3], wires=[wires[q], wires[(q - 1) % num_wires]])

        return circ13

    # ------------------------------------------------------------------
    # Circuit 14: same as 13 but with parametrized CX (H-CP-H) circular
    # params shape: (reps, num_wires, 4)
    # ------------------------------------------------------------------
    elif num == 14:
        def circ14(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires):
                    qp.RY(params[i, q, 0], wires=wires[q])
                for q in range(num_wires):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q, 1], wires=[wires[q], wires[(q + 1) % num_wires]])
                    qp.Hadamard(wires=wires[q])
                for q in range(num_wires):
                    qp.RY(params[i, q, 2], wires=wires[q])
                for q in range(num_wires):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q, 3], wires=[wires[(q - 1) % num_wires], wires[q]])
                    qp.Hadamard(wires=wires[q])

        return circ14

    # ------------------------------------------------------------------
    # Circuit 15: RY, circular CNOT forward, RY, circular CNOT backward
    # params shape: (reps, num_wires, 2) 
    # ------------------------------------------------------------------
    elif num == 15:
        def circ15(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                for q in range(num_wires):
                    qp.RY(params[i, q, 0], wires=wires[q])
                for q in range(num_wires):
                    qp.CNOT(wires=[wires[q], wires[(q + 1) % num_wires]])
                for q in range(num_wires):
                    qp.RY(params[i, q, 1], wires=wires[q])
                for q in range(num_wires):
                    qp.CNOT(wires=[wires[(q - 1) % num_wires], wires[q]])

        return circ15

    # ------------------------------------------------------------------
    # Circuit 16: RX-RZ + staggered parametrized CZ sharing the same angle set
    # (even then odd pairs reuse the same param array — matches Qiskit bug/feature)
    # params shape: (reps, num_wires, 3)
    #   [:, :, :2] = RX-RZ, [:, :num_wires-1, 2] = CP angles (shared even/odd)
    # ------------------------------------------------------------------
    elif num == 16:
        def circ16(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                for q in range(0, num_wires - 1, 2):
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[q + 1]])
                for q in range(1, num_wires - 1, 2):
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[q + 1]])

        return circ16

    # ------------------------------------------------------------------
    # Circuit 17: same as 16 but with parametrized CX (H-CP-H)
    # ------------------------------------------------------------------
    elif num == 17:
        def circ17(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                for q in range(0, num_wires - 1, 2):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[q + 1]])
                    qp.Hadamard(wires=wires[q])
                for q in range(1, num_wires - 1, 2):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[q + 1]])
                    qp.Hadamard(wires=wires[q])

        return circ17

    # ------------------------------------------------------------------
    # Circuit 18: RX-RZ + circular parametrized CZ (wraps around)
    # params shape: (reps, num_wires, 3)
    #   [:, :, :2] = RX-RZ, [:, :, 2] = CP angles (including wrap-around edge)
    # ------------------------------------------------------------------
    elif num == 18:
        def circ18(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                for q in range(num_wires):
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[(q + 1) % num_wires]])

        return circ18

    # ------------------------------------------------------------------
    # Circuit 19: RX-RZ + circular parametrized CX (H-CP-H, wraps around)
    # params shape: (reps, num_wires, 3)  — same layout as circuit 18
    # ------------------------------------------------------------------
    elif num == 19:
        def circ19(params, wires=None):
            reps, num_wires, _ = params.shape
            if wires is None:
                wires = list(range(num_wires))
            for i in range(reps):
                rx_rz_layer(params[i, :, :2], wires)
                for q in range(num_wires):
                    qp.Hadamard(wires=wires[q])
                    qp.ControlledPhaseShift(params[i, q, 2], wires=[wires[q], wires[(q + 1) % num_wires]])
                    qp.Hadamard(wires=wires[q])

        return circ19


    #### back to me and copilot


    # ------------------------------------------------------------------
    # Circuit 31: Perfect SU(4) layers
    # params shape: (num_layers, num_wires//2, 3, 3)
    # ------------------------------------------------------------------

    elif num == 31:
        def perfect_SU4(params, wires = None):
            """ 
            params : tenor of shape (num_layers, num_wires//2, 3, 3)
            """
            if wires is None:
                wires = list(range(params.shape[1]*2))
            num_wires = len(wires)
            num_layers, num_paires, _ , _ = params.shape
            wires_parity = 1 - (num_wires % 2)
            #print(f"num_layers: {num_layers}, num_paires: {num_paires}, wires_parity: {wires_parity}")
            for layer in range(num_layers):
                layer_paires = num_paires - layer % 2 * wires_parity
                layer_wires = wires[layer % 2: layer % 2 + layer_paires * 2]
                #print(f"Layer {layer}: applying SU4 on wires {layer_wires}, paires: {layer_paires}, params shape: {params[layer].shape}")
                for i in range(layer_paires):
                    #print(f"              Applying full_SU2 on wires {layer_wires[2 * i]} and {layer_wires[2 * i + 1]} with params {params[layer, i, :2]}")
                    full_SU2(params[layer, i, :2], wires=[layer_wires[2 * i], layer_wires[2 * i + 1]])

                for i in range(layer_paires):
                    qp.CNOT(wires=[layer_wires[2 * i], layer_wires[2 * i + 1]])
                    qp.RZ(params[layer, i, 2, 0], wires=layer_wires[2 * i])
                    qp.RY(params[layer, i, 2, 1], wires=layer_wires[2 * i + 1])
                    qp.CNOT(wires=[layer_wires[2 * i + 1], layer_wires[2 * i]])
                    qp.RY(params[layer, i, 2, 2], wires=layer_wires[2*i + 1])
                    qp.CNOT(wires=[layer_wires[2 * i], layer_wires[2 * i + 1]])

                # With repetitive layers this is redondant with the next layer.
                #for i in range(num_wires//2):
                #    full_SU2(params[layer, i, 3:5], wires=[wires[2 * i], wires[2 * i + 1]])
        return perfect_SU4
    # ------------------------------------------------------------------
    # Circuit 32: Two rotations + staggered CNOT (brickwall)
    # params shape: (num_layers, num_wires, 2)
    # ------------------------------------------------------------------

    elif num == 32:
        def two_rotations_brickwall(params, wires = None):
            """ 
            params : tenor of shape (num_layers, num_wires, 2)
            """
            num_layers, num_wires, _  = params.shape

            if wires is None:
                wires = list(range(num_wires))
            num_wires = len(wires)
            num_paires = num_wires // 2
            wires_parity = 1 - (num_wires % 2)


            for layer in range(num_layers):
                layer_paires = num_paires - layer % 2 * wires_parity
                layer_wires = wires[layer % 2: layer % 2 + layer_paires * 2]
                two_rotations(params[layer, : layer_paires * 2], wires=layer_wires)
                for i in range(layer_paires):
                    qp.CNOT(wires=[layer_wires[2 * i], layer_wires[2 * i + 1]])
        
        return two_rotations_brickwall
            
    else:
        raise ValueError(f"Circuit number {num} is not defined.")
    

def weight_tensor_shape(num, num_wires, reps = 1):
    # Return the needed shape of the weight tensor for a given circuit number
    if num == 1:
        return (reps, num_wires, 2)
    elif num == 2:
        return (reps, num_wires, 2)
    elif num == 3:
        return (reps, num_wires, 3)
    elif num == 4:  
        return (reps, num_wires, 3)
    elif num == 5:
        return (reps, num_wires, 4 + num_wires - 1)
    elif num == 6:
        return (reps, num_wires, 4 + num_wires - 1)
    elif num == 7:
        return (reps, num_wires, 5)  # plus separate odd CP tensor
    elif num == 8:
        return (reps, num_wires, 5)  # plus separate odd CP tensor
    elif num == 9:
        return (reps, num_wires)
    elif num == 10:
        return (reps, num_wires)
    elif num == 11:
        return (reps, num_wires, 4)
    elif num == 12:
        return (reps, num_wires, 4)
    elif num == 13:
        return (reps, num_wires, 4)
    elif num == 14:
        return (reps, num_wires, 4)
    elif num == 15:
        return (reps, num_wires, 2)
    elif num == 16:
        return (reps, num_wires, 3)
    elif num == 17:
        return (reps, num_wires, 3)
    elif num == 18:
        return (reps, num_wires, 3)
    elif num == 19:
        return (reps, num_wires, 3)
    elif num == 31:
        return (reps, num_wires//2, 3, 3)
    elif num == 32:
        return (reps, num_wires, 2)